services:
    app: &app-service
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - laravel_storage:/var/www/storage
        networks:
            - laravel
        depends_on:
            - postgres
            - redis
        environment: &app-environment
            SSH_PASSPHRASE: ${SSH_PASSPHRASE:-As6d6Cd8d8Xd5WTb}
            DB_CONNECTION: ${DB_CONNECTION:-pgsql}
            DB_HOST: ${DB_HOST:-postgres}
            DB_PORT: ${DB_PORT:-5432}
            DB_DATABASE: ${DB_DATABASE:-vanguard}
            DB_USERNAME: ${DB_USERNAME:-postgres}
            DB_PASSWORD: ${DB_PASSWORD:-password}
            MAIL_MAILER: ${MAIL_MAILER:-smtp}
            MAIL_HOST: ${MAIL_HOST:-127.0.0.1}
            MAIL_PORT: ${MAIL_PORT:-2525}
            MAIL_USERNAME: ${MAIL_USERNAME:-null}
            MAIL_PASSWORD: ${MAIL_PASSWORD:-null}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-"hello@vanguard.test"}
            HORIZON_TOKEN: ${HORIZON_TOKEN:-}
            FLARE_API_KEY: ${FLARE_API_KEY:-}
            ADMIN_EMAIL_ADDRESSES: ${ADMIN_EMAIL_ADDRESSES:-}
            ENABLE_DEVICE_AUTH_ENDPOINT: ${ENABLE_DEVICE_AUTH_ENDPOINT:-true}
            REDIS_HOST: ${REDIS_HOST:-redis}
            REDIS_PORT: ${REDIS_PORT:-6379}
            REVERB_APP_ID: ${REVERB_APP_ID:-your-app-id}
            REVERB_APP_KEY: ${REVERB_APP_KEY:-set-a-key-here}
            REVERB_APP_SECRET: ${REVERB_APP_SECRET:-set-a-secret}
            REVERB_HOST: ${REVERB_HOST:-localhost}
            BROADCAST_CONNECTION: reverb

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "${APP_PORT:-8085}:80"
            - "${APP_SSL_PORT:-8086}:443"
        volumes:
            - ./:/var/www
            - laravel_storage:/var/www/storage
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    postgres:
        image: postgres:15-alpine
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-vanguard}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${DB_USERNAME:-postgres}"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: unless-stopped
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

    horizon:
        <<: *app-service
        container_name: laravel_horizon
        command: php artisan horizon
        depends_on:
            - app
            - postgres
            - redis

    scheduler:
        <<: *app-service
        container_name: laravel_scheduler
        command: /bin/sh -c "while :; do php /var/www/artisan schedule:run --verbose --no-interaction & sleep 60; done"
        depends_on:
            - app
            - postgres
            - redis

    reverb:
        <<: *app-service
        container_name: laravel_reverb
        command: php artisan reverb:start --host=0.0.0.0 --port=8080 --no-interaction
        ports:
            - "8080:8080"
        depends_on:
            - app
            - postgres
            - redis

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
        driver: local
    laravel_storage:
        driver: local
