name: Feature Request
description: Suggest a new feature or enhancement.
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - lewislarsen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the following details to help us understand your request.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: What is the title of the feature you are requesting?
      placeholder: ex. Improve user authentication or add new backup destination
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please describe the feature in detail. What problem does it solve? How will it improve the project?
      placeholder: Provide a detailed description of the feature.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
    validations:
      required: true
  - type: textarea
    id: current-issues
    attributes:
      label: Current Issues
      description: Describe any current issues or limitations that the feature will address.
      placeholder: Describe existing issues or limitations.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context or screenshots related to the feature request.
      placeholder: Add any other context or screenshots here.
    validations:
      required: false
  - type: input
    id: resources
    attributes:
      label: Resources
      description: Provide links to any relevant resources, documentation, or examples.
      placeholder: ex. https://laravel.com/docs
    validations:
      required: false
