name: Refactoring Request
description: Suggest a code refactoring to improve Vanguard.
title: "[Refactor]: "
labels: ["refactor"]
assignees:
  - lewislarsen
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a code refactoring! Please fill out the following details to help us understand your suggestion.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: refactoring-title
    attributes:
      label: Refactoring Title
      description: What is the title of the refactoring you are suggesting?
      placeholder: ex. Improve backup logic
    validations:
      required: true
  - type: textarea
    id: refactoring-description
    attributes:
      label: Refactoring Description
      description: Please describe the refactoring in detail. What code will be affected? How will it improve the application?
      placeholder: Provide a detailed description of the refactoring.
    validations:
      required: true
  - type: textarea
    id: current-issues
    attributes:
      label: Current Issues
      description: Describe any current issues or limitations that the refactoring will address.
      placeholder: Describe existing issues or limitations.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional context or links to related code.
      placeholder: Add any other context or links here.
    validations:
      required: false
