name: Duster Fix
on:
  workflow_call:
  workflow_dispatch:

jobs:
  duster:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # Use `github.ref` for PR refs and `github.head_ref` for normal branches
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      - name: "Duster Fix"
        uses: tighten/duster-action@v3
        with:
          args: fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto_commit_action
        with:
          commit_message: "style: automated changes to code style"
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com

      - name: Ignore Duster commit in git blame
        if: steps.auto_commit_action.outputs.changes_detected == 'true'
        run: echo ${{ steps.auto_commit_action.outputs.commit_hash }} >> .git-blame-ignore-revs

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: ignoring commit change in git blame"
          commit_user_name: GitHub Action
          commit_user_email: actions@github.com
