name: Main CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  duster:
    uses: ./.github/workflows/duster-fix-blame.yml

  static-analysis:
    needs: duster
    uses: ./.github/workflows/static-analysis.yml

  rector:
    needs: static-analysis
    uses: ./.github/workflows/run-rector.yml

  test-suite:
    needs: rector
    uses: ./.github/workflows/test-suite.yml

  ci-passed:
    needs: [duster, static-analysis, rector, test-suite]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All CI checks passed!"
